# Keys for LocalizationManger to use in source code: MIT License
# @author Vladimir Petrenko
@tool
class_name LocalizationKeys

const GROUND_TOWER = "GROUND_TOWER"
const CANOPY_TOWER = "CANOPY_TOWER"
const THORN_WALL = "THORN_WALL"
const TOXIC_BLOOM = "TOXIC_BLOOM"
const PITCHER_PLANT = "PITCHER_PLANT"
const FLYTRAP_CLUSTER = "FLYTRAP_CLUSTER"
const THORN_VINES = "THORN_VINES"
const TOXIC_SPORE = "TOXIC_SPORE"
const BOMBER_FRUIT = "BOMBER_FRUIT"
const SEED_BOMBER = "SEED_BOMBER"
const WATER_COLLECTED = "WATER_COLLECTED"
const OBSTICLE_HIT = "OBSTICLE_HIT"
const OBSTICLE_INSTRUCTIONS = "OBSTICLE_INSTRUCTIONS"
const OBSTICLE_HIT_LEFT = "OBSTICLE_HIT_LEFT"
const TIME_UP = "TIME_UP"
const ROOT_RESULTS = "ROOT_RESULTS"
const GO_TO_GROWTH = "GO_TO_GROWTH"
const GO_TO_ROOT = "GO_TO_ROOT"
const UNDEAD_SMALL_ANIMAL = "UNDEAD_SMALL_ANIMAL"
const UNDEAD_HUMAN = "UNDEAD_HUMAN"
const UNDEAD_LARGE_ANIMAL = "UNDEAD_LARGE_ANIMAL"
const UNDEAD_ANCIENT_CREATURE = "UNDEAD_ANCIENT_CREATURE"
const UNDEAD_DINOSAUR = "UNDEAD_DINOSAUR"
const ROTATE_LANDSCAPE = "ROTATE_LANDSCAPE"
const ROTATE_PORTRAIT = "ROTATE_PORTRAIT"
const SPORE_SPRAYER = "SPORE_SPRAYER"
const CLOSE = "CLOSE"
const BUILD = "BUILD"
const NOT_ENOUGH_MONEY = "NOT_ENOUGH_MONEY"
const GROUND = "GROUND"
const CANOPY = "CANOPY"
const TURNING_DESCRIPTION = "TURNING_DESCRIPTION"
const WORLD_TUTORIAL_1 = "WORLD_TUTORIAL_1"
const WORLD_TUTORIAL_2 = "WORLD_TUTORIAL_2"
const WORLD_TUTORIAL_3 = "WORLD_TUTORIAL_3"
const WORLD_TUTORIAL_4 = "WORLD_TUTORIAL_4"
const OVERWORLD_TUTORIAL_1 = "OVERWORLD_TUTORIAL_1"
const OVERWORLD_TUTORIAL_2 = "OVERWORLD_TUTORIAL_2"
const OVERWORLD_TUTORIAL_3 = "OVERWORLD_TUTORIAL_3"
const OVERWORLD_TUTORIAL_4 = "OVERWORLD_TUTORIAL_4"

const KEYS = [
 "GROUND_TOWER",
 "CANOPY_TOWER",
 "THORN_WALL",
 "TOXIC_BLOOM",
 "PITCHER_PLANT",
 "FLYTRAP_CLUSTER",
 "THORN_VINES",
 "TOXIC_SPORE",
 "BOMBER_FRUIT",
 "SEED_BOMBER",
 "WATER_COLLECTED",
 "OBSTICLE_HIT",
 "OBSTICLE_INSTRUCTIONS",
 "OBSTICLE_HIT_LEFT",
 "TIME_UP",
 "ROOT_RESULTS",
 "GO_TO_GROWTH",
 "GO_TO_ROOT",
 "UNDEAD_SMALL_ANIMAL",
 "UNDEAD_HUMAN",
 "UNDEAD_LARGE_ANIMAL",
 "UNDEAD_ANCIENT_CREATURE",
 "UNDEAD_DINOSAUR",
 "ROTATE_LANDSCAPE",
 "ROTATE_PORTRAIT",
 "SPORE_SPRAYER",
 "CLOSE",
 "BUILD",
 "NOT_ENOUGH_MONEY",
 "GROUND",
 "CANOPY",
 "TURNING_DESCRIPTION",
 "WORLD_TUTORIAL_1",
 "WORLD_TUTORIAL_2",
 "WORLD_TUTORIAL_3",
 "WORLD_TUTORIAL_4",
 "OVERWORLD_TUTORIAL_1",
 "OVERWORLD_TUTORIAL_2",
 "OVERWORLD_TUTORIAL_3",
 "OVERWORLD_TUTORIAL_4"
]