# Keys for LocalizationManger to use in source code: MIT License
# @author Vladimir Petrenko
@tool
class_name LocalizationKeys

const PICK_TOWER = "PICK_TOWER"
const THORN_WALL = "THORN_WALL"
const TOXIC_BLOOM = "TOXIC_BLOOM"
const PITCHER_PLANT = "PITCHER_PLANT"
const FLYTRAP_CLUSTER = "FLYTRAP_CLUSTER"
const THORN_VINES = "THORN_VINES"
const TOXIC_SPORE = "TOXIC_SPORE"
const BOMBER_FRUIT = "BOMBER_FRUIT"
const SEED_BOMBER = "SEED_BOMBER"
const WATER_COLLECTED = "WATER_COLLECTED"
const OBSTICLE_HIT = "OBSTICLE_HIT"
const OBSTICLE_INSTRUCTIONS = "OBSTICLE_INSTRUCTIONS"
const OBSTICLE_HIT_LEFT = "OBSTICLE_HIT_LEFT"
const TIME_UP = "TIME_UP"
const ROOT_RESULTS = "ROOT_RESULTS"
const GO_TO_GROWTH = "GO_TO_GROWTH"
const GO_TO_ROOT = "GO_TO_ROOT"
const UNDEAD_SMALL_ANIMAL = "UNDEAD_SMALL_ANIMAL"
const UNDEAD_HUMAN = "UNDEAD_HUMAN"
const UNDEAD_LARGE_ANIMAL = "UNDEAD_LARGE_ANIMAL"
const UNDEAD_ANCIENT_CREATURE = "UNDEAD_ANCIENT_CREATURE"
const UNDEAD_DINOSAUR = "UNDEAD_DINOSAUR"

const KEYS = [
 "PICK_TOWER",
 "THORN_WALL",
 "TOXIC_BLOOM",
 "PITCHER_PLANT",
 "FLYTRAP_CLUSTER",
 "THORN_VINES",
 "TOXIC_SPORE",
 "BOMBER_FRUIT",
 "SEED_BOMBER",
 "WATER_COLLECTED",
 "OBSTICLE_HIT",
 "OBSTICLE_INSTRUCTIONS",
 "OBSTICLE_HIT_LEFT",
 "TIME_UP",
 "ROOT_RESULTS",
 "GO_TO_GROWTH",
 "GO_TO_ROOT",
 "UNDEAD_SMALL_ANIMAL",
 "UNDEAD_HUMAN",
 "UNDEAD_LARGE_ANIMAL",
 "UNDEAD_ANCIENT_CREATURE",
 "UNDEAD_DINOSAUR"
]
